export const LOADING_ERROR = "LOADING_ERROR";
export const LOADING_IN_PROGRESS = "LOADING_IN_PROGRESS";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const CHANGE_SEARCH = "CHANGE_SEARCH";
export const CLEAR_NEWS = "CLEAR_NEWS";
